// Auto-generated by UIBridge. Do not edit manually.

import React from "react";

// 위젯 타입별 컴포넌트 매핑
const widgetMap = {
  Container: "div",
  Button: "button",
  Label: "span",
  Image: "img",
  ImageSeqOpt: "div"
};

// Tailwind 스타일 변환 예시 (실제 프로젝트에 맞게 확장 가능)
function getTailwindStyle(widget) {
  let style = "";
  if (widget.type === "Container") style += "flex flex-col ";
  if (widget.type === "Button") style += "px-4 py-2 bg-blue-500 text-white rounded ";
  if (widget.type === "Label") style += "text-base ";
  if (widget.type === "Image") style += "w-16 h-16 object-contain ";
  // 추가 스타일 변환 로직 필요시 여기에 작성
  return style.trim();
}

// IR → React Element 변환
export function irToReact(ir, widgetById = {}) {
  if (!ir || !ir.widgets) return null;
  // id로 위젯 빠른 조회
  if (Object.keys(widgetById).length === 0) {
    ir.widgets.forEach(w => { widgetById[w.id] = w; });
  }
  // 루트 위젯만 렌더링
  const roots = ir.widgets.filter(w => w.parent === "NULL");
  return roots.map(root => renderWidget(root, widgetById));
}

function renderWidget(widget, widgetById) {
  const Comp = widgetMap[widget.type] || "div";
  const style = getTailwindStyle(widget);
  // children id 배열을 실제 컴포넌트로 변환
  const children = widget.children && widget.children.length > 0
    ? widget.children.map(cid => widgetById[cid] ? renderWidget(widgetById[cid], widgetById) : null)
    : null;
  // props 순서: id → text → src → style → children
  const props = {
    id: widget.id,
    className: style
  };
  if (widget.text) props.children = widget.text;
  if (widget.type === "Image" && widget.src) props.src = widget.src;
  // children 추가
  if (children) props.children = [props.children, ...children].filter(Boolean);
  return React.createElement(Comp, props);
}
