// Auto-generated by UIBridge. Do not edit manually.

/**
 * IR 객체를 받아 JSX 코드(문자열)로 변환합니다.
 * @param {object} ir - Intermediate Representation
 * @param {string} screenName - 생성할 컴포넌트 이름
 * @returns {string} JSX 코드
 */
export function irToJsx(ir, screenName = "ScreenMain") {
  if (!ir || !ir.widgets || ir.widgets.length === 0) return "";
  const widgetMap = {
    Container: "div",
    Button: "button",
    Label: "span",
    Image: "img",
    ImageSeqOpt: "div"
  };
  // id로 위젯 빠른 조회
  const widgetById = {};
  ir.widgets.forEach(w => { widgetById[w.id] = w; });
  // screenId와 일치하는 Container만 루트로 사용
  const root = ir.widgets.find(w => w.type === "Container" && w.id.includes(ir.screenId));
  function renderWidgetJsx(widget, depth = 2) {
    const Comp = widgetMap[widget.type] || "div";
    const style = getTailwindStyle(widget);
    let props = `id=\"${widget.id}\" className=\"${style}\"`;
    if (widget.type === "Image" && widget.src) props += ` src=\"${widget.src}\"`;
    let childrenJsx = "";
    const pad = " ".repeat(depth);
    if (widget.text) childrenJsx += widget.text;
    if (widget.children && widget.children.length > 0) {
      childrenJsx += "\n" + widget.children.map(cid => widgetById[cid] ? renderWidgetJsx(widgetById[cid], depth + 2) : "").join("\n") + "\n" + pad;
    }
    if (["img"].includes(Comp)) {
      return pad + `<${Comp} ${props} />`;
    }
    if (childrenJsx) {
      return pad + `<${Comp} ${props}>\n${pad}  ${childrenJsx}\n${pad}</${Comp}>`;
    }
    return pad + `<${Comp} ${props}></${Comp}>`;
  }
  function getTailwindStyle(widget) {
    let style = "";
    if (widget.type === "Container") style += "flex flex-col ";
    if (widget.type === "Button") style += "px-4 py-2 bg-blue-500 text-white rounded ";
    if (widget.type === "Label") style += "text-base ";
    if (widget.type === "Image") style += "w-16 h-16 object-contain ";
    // layout 정보 Tailwind로 변환
    if (widget.layout) {
      if (typeof widget.layout.x === "number") style += `left-[${widget.layout.x}px] `;
      if (typeof widget.layout.y === "number") style += `top-[${widget.layout.y}px] `;
      if (typeof widget.layout.w === "number") style += `w-[${widget.layout.w}px] `;
      if (typeof widget.layout.h === "number") style += `h-[${widget.layout.h}px] `;
    }
    // style 정보 Tailwind로 변환
    if (widget.style) {
      if (widget.style.bgColor) {
        const hex = widget.style.bgColor.replace("0x", "#");
        style += `bg-[${hex}] `;
      }
      if (widget.style.font) {
        style += `font-[${widget.style.font}] `;
      }
      if (widget.style.fontSize) {
        style += `text-[${widget.style.fontSize}px] `;
      }
      if (widget.style.fontWeight) {
        style += `font-[${widget.style.fontWeight}] `;
      }
      if (widget.style.color) {
        const hex = widget.style.color.replace("0x", "#");
        style += `text-[${hex}] `;
      }
      if (widget.style.borderColor) {
        const hex = widget.style.borderColor.replace("0x", "#");
        style += `border border-solid border-[${hex}] `;
      }
      if (widget.style.borderWidth) {
        style += `border-[${widget.style.borderWidth}px] `;
      }
      if (widget.style.radius) {
        style += `rounded-[${widget.style.radius}px] `;
      }
      if (widget.style.opacity) {
        style += `opacity-[${widget.style.opacity}] `;
      }
    }
    return style.trim();
  }
  const jsxBody = root ? renderWidgetJsx(root, 2) : "";
  return `// Auto-generated by UIBridge. Do not edit manually.\n\nimport React from \"react\";\n\nconst ${screenName} = () => (\n  <>\n${indentMultiline(jsxBody, 2)}\n  </>\n);\n\nexport default ${screenName};\n`;
}

function indentMultiline(str, spaces = 2) {
  const pad = " ".repeat(spaces);
  return str.split("\n").map(line => pad + line).join("\n");
}
