// Auto-generated by UIBridge. Do not edit manually.

import React from "react";

const Screen_CM_Confirmation = () => (
  <div className="flex flex-col items-center justify-center bg-black min-h-screen">
    <img src="/images/img_info.png" className="w-16 h-16 mb-4" alt="icon" />
    <span className="text-white text-xl font-medium my-4">Description Description</span>
    <div className="flex flex-row gap-4 mt-6">
      <button className="px-6 py-2 rounded-xl bg-gray-700 text-white text-lg font-medium m-2">Button</button>
      <button className="px-6 py-2 rounded-xl bg-gray-700 text-white text-lg font-medium m-2">Button</button>
    </div>
  </div>
);

export default Screen_CM_Confirmation;
